"""Add feature_count and geojson fields

Revision ID: 732e9afa116a
Revises: 001
Create Date: 2026-01-07 13:15:12.736806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732e9afa116a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('feature_count', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('layers', sa.Column('geojson', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'geojson')
    op.drop_column('layers', 'feature_count')
    # ### end Alembic commands ###
